Test reporting

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -44,7 +44,13 @@ jobs:
       run: dotnet build ${{ env.solution }} --no-restore
     
     - name: Test
-      run: dotnet test ${{ env.solution }} --no-build --verbosity normal
+      run: dotnet test ${{ env.solution }} --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
+    
+    - uses: actions/upload-artifact@v2  # upload test results
+      if: success() || failure()        # run this step even if previous step failed
+      with:
+          name: test-results
+          path: test-results.trx
 
     - name: Perform CodeQL Analysis
       uses: github/codeql-action/analyze@v2
